version: '3.7'

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/usr/src/openfacstrack/
      - static_volume:/home/openfacstrack/web/static
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - keycloak
    network_mode: "host"

  keycloak:
    image: jboss/keycloak
    volumes:
      - ./keycloak/openfacstrack-realm.prod.json:/tmp/openfacstrack-realm.json
    env_file:
      - .env.prod
    command: -Djgroups.bind_addr=127.0.0.1 -b=0.0.0.0
    ports:
      - 8080:8080
    network_mode: "host"

  nginx:
    build: nginx
    volumes:
      - static_volume:/home/openfacstrack/web/static
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:433
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web
    network_mode: "host"

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_volume:
