version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./init.dev.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=openfacstrack
      - POSTGRES_PASSWORD=openfacstrack
      - POSTGRES_DB=openfacstrack
  keycloak:
    image: jboss/keycloak
    volumes:
    - ./keycloak/openfacstrack-realm.dev.json:/tmp/openfacstrack-realm.json
    env_file:
      - .env.dev
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      default:
        aliases:
             - keycloak.localhost
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/usr/src/openfacstrack/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
      - keycloak

volumes:
  postgres_data: