version: '3.7'

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/usr/src/openfacstrack/
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - keycloak
  keycloak:
    image: jboss/keycloak
    volumes:
      - ./keycloak/openfacstrack-realm.json:/tmp/openfacstrack-realm.json
    env_file:
      - .env.prod
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      default:
        aliases:
          - keycloak.localhost
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=openfacstrack
      - POSTGRES_PASSWORD=openfacstrack
      - POSTGRES_DB=openfacstrack
  nginx:
    build: nginx
    volumes:
      - static_volume:/home/openfacstrack/web/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: