# pull official base image
FROM python:3.8-slim

# set work directory
WORKDIR /usr/src/openfacstrack

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies

RUN pip install --upgrade pip
COPY requirements.txt /usr/src/openfacstrack/requirements.txt
RUN set -ex \
    && BUILD_DEPS=" \
    build-essential \
    libpcre3-dev \
    libpq-dev \
    " \
    && apt-get update && apt-get install -y --no-install-recommends $BUILD_DEPS \
    && pip install -r requirements.txt

RUN apt-get install -y netcat
RUN rm -rf /var/lib/apt/lists/*
# copy entrypoint.dev.sh
COPY docker/entrypoint.dev.sh /usr/src/openfacstrack/entrypoint.dev.sh

# copy project
COPY . /usr/src/openfacstrack/

# run entrypoint.dev.sh
ENTRYPOINT ["/usr/src/openfacstrack/docker/entrypoint.dev.sh"]
