# Generated by Django 3.0.3 on 2020-04-22 09:30

from django.db import migrations, models
import django.db.models.deletion
import openfacstrack.apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', openfacstrack.apps.core.models.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', openfacstrack.apps.core.models.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('covid_patient_id', models.TextField()),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalSampleMetadataDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', openfacstrack.apps.core.models.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', openfacstrack.apps.core.models.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', openfacstrack.apps.core.models.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', openfacstrack.apps.core.models.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', openfacstrack.apps.core.models.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', openfacstrack.apps.core.models.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('data_type', models.CharField(choices=[('Numeric', 'Numeric'), ('Text', 'Text')], max_length=10)),
                ('internal_name', models.CharField(max_length=255)),
                ('public_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('excel_column_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_reference_parameter', models.BooleanField(blank=True, null=True)),
                ('gating_hierarchy', models.TextField()),
                ('unit', models.CharField(max_length=255)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Panel')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessedSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', openfacstrack.apps.core.models.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', openfacstrack.apps.core.models.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_acquired', models.DateField()),
                ('biobank_id', models.CharField(max_length=12)),
                ('n_heparin_tubes', models.IntegerField(blank=True, null=True)),
                ('n_paxgene_tubes', models.IntegerField(blank=True, null=True)),
                ('bleed_time', models.TimeField(blank=True, null=True)),
                ('processed_time', models.TimeField(blank=True, null=True)),
                ('blood_vol', models.FloatField(blank=True, null=True)),
                ('lymph_conc_as_MLNmL', models.FloatField(blank=True, null=True)),
                ('total_lymph', models.FloatField(blank=True, null=True)),
                ('vol_frozen_mL', models.FloatField(blank=True, null=True)),
                ('freeze_time', models.TimeField(blank=True, null=True)),
                ('operator1', models.CharField(max_length=255)),
                ('operator2', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('real_pbmc_frozen_stock_conc_MLNmL', models.FloatField(blank=True, null=True)),
                ('clinical_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.ClinicalSample')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', openfacstrack.apps.core.models.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', openfacstrack.apps.core.models.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.TextField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Parameter')),
                ('processed_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.ProcessedSample')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoredSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', openfacstrack.apps.core.models.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', openfacstrack.apps.core.models.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('stored_sample_id', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('type_of_stored_material', models.CharField(max_length=255)),
                ('from_which_tube_type', models.CharField(max_length=255)),
                ('freezer', models.CharField(max_length=255)),
                ('box', models.IntegerField()),
                ('row', models.IntegerField()),
                ('position', models.IntegerField()),
                ('comments', models.TextField()),
                ('processed_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.ProcessedSample')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PanelMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', openfacstrack.apps.core.models.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', openfacstrack.apps.core.models.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Panel')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumericParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', openfacstrack.apps.core.models.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', openfacstrack.apps.core.models.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.FloatField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Parameter')),
                ('processed_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.ProcessedSample')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', openfacstrack.apps.core.models.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', openfacstrack.apps.core.models.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('fcs_file_name', models.CharField(max_length=255)),
                ('fcs_file_location', models.CharField(max_length=255)),
                ('is_in_FlowRepository', models.BooleanField(blank=True, null=True)),
                ('is_automated_gating_done', models.BooleanField(blank=True, null=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Panel')),
                ('processed_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.ProcessedSample')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalSampleMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', openfacstrack.apps.core.models.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', openfacstrack.apps.core.models.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('metadata_value', models.CharField(max_length=255)),
                ('clinical_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.ClinicalSample')),
                ('metadata_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.ClinicalSampleMetadataDict')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
