# Generated by Django 3.0.3 on 2020-05-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='data_type',
            field=models.CharField(choices=[('PanelNumeric', 'Numeric parameter from panel'), ('SampleNumeric', 'Numeric metadata from sample'), ('DerivedNumeric', 'Numeric derived parameter from panel'), ('Text', 'Text'), ('Date', 'Date'), ('Derived', 'Derived'), ('Other', 'Other')], max_length=20),
        ),
    ]
