# Generated by Django 3.0.3 on 2020-04-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameter",
            name="gating_hierarchy",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parameter",
            name="unit",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
