# Generated by Django 3.0.3 on 2020-04-29 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0002_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedsample",
            name="batch",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processedsample",
            name="uploaded_file",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="track.UploadedFile",
            ),
            preserve_default=False,
        ),
    ]
