# Generated by Django 3.0.3 on 2020-04-08 19:58

from django.db import migrations


def load_panel_data(apps, schema_editor):
    import pandas as pd
    import os

    # Read xls or csv file and append panels and parameters
    # Hard-coding filename here initially
    df_panels = pd.read_excel("./sample_data/population_names_200331.xlsx", skiprows=1)

    # Store panel names in Panel table
    panel_names = [p.upper() for p in df_panels.panel.unique().tolist()]
    panel_names.sort()

    Panel = apps.get_model("track", "Panel")
    for panel_name in panel_names:
        panel = Panel()
        panel.name = panel_name
        panel.save()

    # Store parameter details
    Parameter = apps.get_model("track", "Parameter")
    for index, row in df_panels.iterrows():
        parameter = Parameter()
        panel = Panel.objects.get(name=row["panel"].upper())
        parameter.panel = panel

        parameter.internal_name = row["marker string"]
        parameter.public_name = row["public_population_name"]
        # parameter.display_name = row['presented on webpage as'] - unit?
        # parameter.excel_column_name = ???
        # parameter.description = ???
        parameter.is_reference_parameter = False  # Where do we get this ???
        parameter.gating_hierarchy = row["gating hierarchy"]
        parameter.unit = row["presented on webpage as"]
        # What is 'ancestral population when preseneted as fraction' ?
        parameter.save()


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0002_add_gating_heirarchy_and_unit"),
    ]

    operations = [migrations.RunPython(load_panel_data)]
