# Generated by Django 3.0.3 on 2020-04-17 09:35

from django.db import migrations, models
import django.db.models.deletion
import openfacstrack.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_ingest_panel_from_spreadsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', openfacstrack.apps.core.models.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', openfacstrack.apps.core.models.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('covid_patient_id', models.TextField()),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalSampleMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', openfacstrack.apps.core.models.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', openfacstrack.apps.core.models.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('metadata_value', models.CharField(max_length=255)),
                ('clinical_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.ClinicalSample')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalSampleMetadataDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', openfacstrack.apps.core.models.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', openfacstrack.apps.core.models.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='processedsample',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='clinicalsamplemetadata',
            name='metadata_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.ClinicalSampleMetadataDict'),
        ),
        migrations.AddField(
            model_name='processedsample',
            name='clinical_sample',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='track.ClinicalSample'),
            preserve_default=False,
        ),
    ]
