# Generated by Django 3.0.5 on 2020-04-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_auto_20200429_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='row_number',
            field=models.IntegerField(default=0),
        ),
    ]
