# Generated by Django 3.0.3 on 2020-04-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_auto_20200417_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panelmetadata',
            old_name='name',
            new_name='key',
        ),
        migrations.AddField(
            model_name='panelmetadata',
            name='value',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicalsamplemetadatadict',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
