# Generated by Django 3.0.5 on 2020-04-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_uploadedfile_row_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationentry',
            name='entry_type',
            field=models.CharField(choices=[('INFO', 'INFO'), ('ERROR', 'ERROR')], default='INFO', max_length=12),
        ),
    ]
