# Generated by Django 3.0.3 on 2020-04-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_auto_20200420_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedsample',
            name='bleed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedsample',
            name='blood_vol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedsample',
            name='freeze_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedsample',
            name='lymph_conc_as_MLNmL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedsample',
            name='n_heparin_tubes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedsample',
            name='n_paxgene_tubes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedsample',
            name='processed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedsample',
            name='real_pbmc_frozen_stock_conc_MLNmL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedsample',
            name='total_lymph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedsample',
            name='vol_frozen_mL',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
