# Generated by Django 3.0.5 on 2020-04-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_validationentry_validation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='content',
            field=models.BinaryField(blank=True),
        ),
    ]
