# Generated by Django 3.0.5 on 2020-04-30 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openfacstrack.apps.track.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0008_auto_20200429_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='content',
            field=models.FileField(blank=True, upload_to=openfacstrack.apps.track.models.user_directory_path),
        ),
    ]
