# Generated by Django 3.0.5 on 2020-04-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_auto_20200430_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationentry',
            name='entry_type',
            field=models.CharField(choices=[('INFO', 'INFO'), ('ERROR', 'ERROR'), ('WARN', 'WARN')], default='INFO', max_length=12),
        ),
    ]
