# Generated by Django 3.0.5 on 2020-04-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_auto_20200430_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='valid_model',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='valid_syntax',
            field=models.BooleanField(default=True),
        ),
    ]
